using System.Collections.Generic;

namespace ClaudeWatch.App;

/// <summary>
/// Every visible word in one place, in English and Persian. Bindings go through
/// the indexer (<c>{Binding L[Nav_Dashboard]}</c>), so switching language is a
/// single property change on the view model.
/// </summary>
public sealed class Strings
{
    private string _language = "en";

    public string Language
    {
        get => _language;
        set => _language = value == "fa" ? "fa" : "en";
    }

    public bool IsRightToLeft => _language == "fa";

    public string this[string key]
    {
        get
        {
            var table = _language == "fa" ? Fa : En;
            if (table.TryGetValue(key, out var value))
            {
                return value;
            }

            return En.TryGetValue(key, out var fallback) ? fallback : key;
        }
    }

    public string Get(string key) => this[key];

    private static readonly Dictionary<string, string> En = new()
    {
        ["App_Name"] = "Claude Watch",
        ["App_Tagline"] = "VPN and clock guard",

        ["Nav_Dashboard"] = "Dashboard",
        ["Nav_Processes"] = "Processes",
        ["Nav_Network"] = "Network",
        ["Nav_Activity"] = "Activity",
        ["Nav_Settings"] = "Settings",
        ["Nav_About"] = "About",

        ["Head_Ready"] = "Protected",
        ["Head_Blocked"] = "Blocked",
        ["Head_Standby"] = "Standby",
        ["Head_Mismatch"] = "Clock mismatch",
        ["Head_Paused"] = "Paused",
        ["Head_Off"] = "Guard off",

        ["Msg_Ready"] = "VPN is up and the clock matches. Claude is free to run.",
        ["Msg_Blocked"] = "No VPN detected. Claude is stopped and stays stopped.",
        ["Msg_Standby"] = "Home time is back while Claude is closed. Prepare before you open it.",
        ["Msg_Mismatch"] = "The system clock is not the zone this session needs.",
        ["Msg_Paused"] = "All rules are paused. Nothing will be stopped.",
        ["Msg_Off"] = "Both rules are switched off in Settings.",

        ["Tile_Vpn"] = "VPN",
        ["Tile_Clock"] = "System clock",
        ["Tile_Claude"] = "Claude",
        ["Vpn_None"] = "Not connected",
        ["Clock_Target"] = "Needs",
        ["Clock_Home"] = "Home",
        ["Clock_Work"] = "Work",
        ["Clock_Matches"] = "Matches",
        ["Claude_None"] = "Not running",
        ["Claude_Running"] = "running",

        ["Btn_Open"] = "Open Claude",
        ["Btn_Stop"] = "Stop Claude",
        ["Btn_Prepare"] = "Prepare work time",
        ["Btn_HoldHome"] = "Back to home time",
        ["Btn_Pause"] = "Pause guard",
        ["Btn_Resume"] = "Resume guard",
        ["Btn_ChangeNow"] = "Change the clock",
        ["Btn_SkipSession"] = "Skip clock rules",
        ["Btn_RestoreRules"] = "Restore clock rules",
        ["Btn_Refresh"] = "Refresh",
        ["Btn_Save"] = "Save changes",
        ["Btn_Saved"] = "Saved",
        ["Btn_Reset"] = "Reset to defaults",
        ["Btn_Export"] = "Export",
        ["Btn_Clear"] = "Clear",
        ["Btn_Browse"] = "Browse",
        ["Btn_Install"] = "Set up now",
        ["Btn_Remove"] = "Remove",
        ["Btn_Trust"] = "Trust",
        ["Btn_Untrust"] = "Untrust",
        ["Btn_Ignore"] = "Ignore",
        ["Btn_Unignore"] = "Stop ignoring",
        ["Btn_StopOne"] = "Stop",
        ["Btn_Close"] = "Close",
        ["Btn_Minimize"] = "Minimize",

        ["Banner_ClockNeeded"] = "The clock needs to change",
        ["Banner_ClockDetail"] = "Windows asks for approval once, then the guard continues.",
        ["Banner_Failed"] = "The last change did not go through. Claude stays blocked.",
        ["Banner_Paused"] = "Guard paused until",

        ["Pause_15"] = "15 minutes",
        ["Pause_30"] = "30 minutes",
        ["Pause_60"] = "1 hour",

        ["Proc_Title"] = "Matching processes",
        ["Proc_Empty"] = "Nothing matching is running.",
        ["Proc_Pid"] = "PID",
        ["Proc_Memory"] = "Memory",
        ["Proc_Started"] = "Started",
        ["Proc_StopAll"] = "Stop all",
        ["Proc_Hint"] = "Matching is on the program name only, so a script that merely mentions Claude is never touched.",

        ["Net_Title"] = "Network adapters",
        ["Net_Hint"] = "Green means this adapter counts as your VPN right now. Trust one to force it, ignore one to rule it out.",
        ["Net_Counts"] = "Counts as VPN",
        ["Net_Up"] = "Up",
        ["Net_Down"] = "Down",
        ["Net_Trusted"] = "Trusted",
        ["Net_Ignored"] = "Ignored",
        ["Net_Idle"] = "No traffic",
        ["Net_Empty"] = "No adapters were found.",

        ["Act_Title"] = "Activity",
        ["Act_Empty"] = "Nothing has happened yet.",
        ["Act_Hint"] = "Kept for",
        ["Act_Days"] = "days",

        ["Set_Protection"] = "Protection",
        ["Set_EnforceVpn"] = "Require a VPN",
        ["Set_EnforceVpn_Sub"] = "Stop Claude the moment the tunnel drops.",
        ["Set_EnforceTz"] = "Require the work time zone",
        ["Set_EnforceTz_Sub"] = "Keep the system clock in the zone below while Claude runs.",
        ["Set_Action"] = "When a rule breaks",
        ["Set_Action_Stop"] = "Stop Claude",
        ["Set_Action_Warn"] = "Only warn me",
        ["Set_Tolerance"] = "Ignore short VPN drops for",
        ["Set_Tolerance_Sub"] = "Claude is blocked immediately either way; this only delays changing the clock.",
        ["Set_Checks"] = "checks",
        ["Set_Interval"] = "Check every",
        ["Set_Seconds"] = "seconds",

        ["Set_Zones"] = "Time zones",
        ["Set_WorkZone"] = "Work zone (VPN connected)",
        ["Set_HomeZone"] = "Home zone (VPN off)",
        ["Set_TzMode"] = "Changing the clock",
        ["Set_TzMode_Ask"] = "Ask me first",
        ["Set_TzMode_Auto"] = "Change it automatically",
        ["Set_TzMode_Report"] = "Never change it",
        ["Set_Helper"] = "Skip the approval prompt",
        ["Set_Helper_Sub"] = "Registers two scheduled tasks that switch the clock with administrator rights. Windows asks once during setup, then never again.",
        ["Set_Helper_On"] = "Set up",
        ["Set_Helper_Off"] = "Not set up",

        ["Set_Detection"] = "Detection",
        ["Set_VpnPattern"] = "VPN adapter pattern",
        ["Set_ProcPattern"] = "Claude process pattern",
        ["Set_Extra"] = "Also treat as Claude",
        ["Set_Excluded"] = "Never stop",
        ["Set_CommaHint"] = "Separate names with commas.",
        ["Set_Tunnels"] = "Count any tunnel or dial-up adapter as a VPN",
        ["Set_Routed"] = "Only count a tunnel while it carries your traffic",
        ["Set_Routed_Sub"] = "Tailscale, ZeroTier and the like stay connected all day to reach other machines without moving your browsing anywhere. With this on, a tunnel your traffic is not going through does not count as protection. An adapter you marked as trusted still counts either way.",
        ["Set_BadPattern"] = "That pattern is not valid.",

        ["Set_App"] = "Application",
        ["Set_Startup"] = "Start with Windows",
        ["Set_StartMin"] = "Start hidden in the tray",
        ["Set_MinTray"] = "Minimize to the tray",
        ["Set_CloseTray"] = "Keep running when the window closes",
        ["Set_Notify"] = "Show notifications",
        ["Set_NotifyProblems"] = "Only for problems",
        ["Set_Sound"] = "Play a sound with alerts",
        ["Set_Confirm"] = "Ask before I stop Claude by hand",
        ["Set_Hotkey"] = "Ctrl+Alt+K stops Claude from anywhere",
        ["Set_ClaudePath"] = "Claude program",
        ["Set_ClaudePath_Auto"] = "Found automatically",
        ["Set_ClaudePath_Missing"] = "Not found — pick it by hand",

        ["Set_Look"] = "Appearance",
        ["Set_Theme"] = "Theme",
        ["Set_Theme_Dark"] = "Dark",
        ["Set_Theme_Light"] = "Light",
        ["Set_Theme_System"] = "Follow Windows",
        ["Set_Accent"] = "Accent",
        ["Set_Language"] = "Language",

        ["Set_Advanced"] = "Housekeeping",
        ["Set_Retention"] = "Keep the activity log for",
        ["Set_DataFolder"] = "Open the data folder",
        ["Set_ResetHint"] = "Puts every setting back the way it started.",

        ["About_What"] = "What this does",
        ["About_Body"] = "Claude Watch keeps two conditions true while the Claude desktop app is open: a VPN tunnel is up, and the system clock sits in your work zone. If either one breaks, every matching Claude process is stopped and the clock is put back to your home zone.",
        ["About_Warning"] = "This app stops processes and changes the system clock. Both are deliberate. Changing the clock needs Windows approval unless you set up the shortcut in Settings.",
        ["About_Credit"] = "Built on the claude-watch script by omidkorat.",
        ["About_Version"] = "Version",
        ["About_Source"] = "Original script",
        ["About_Admin"] = "Running as administrator",
        ["About_NotAdmin"] = "Running as a normal user",

        ["Tray_Open"] = "Open Claude Watch",
        ["Tray_Stop"] = "Stop Claude now",
        ["Tray_Pause"] = "Pause for 30 minutes",
        ["Tray_Resume"] = "Resume the guard",
        ["Tray_Exit"] = "Quit",
        ["Tray_Running"] = "Claude Watch is still running in the tray.",

        ["Confirm_Stop"] = "Stop every running Claude process?",
        ["Confirm_Title"] = "Claude Watch",
        ["Confirm_Reset"] = "Put every setting back to its default?",

        ["Notify_Stopped"] = "Claude was stopped",
        ["Notify_VpnLost"] = "VPN dropped",
        ["Notify_VpnBack"] = "VPN is back",
        ["Notify_ClockChanged"] = "Clock changed",

        ["Grace_Vpn"] = "VPN disconnected",
        ["Grace_Clock"] = "The clock is wrong",
        ["Grace_Body"] = "Claude's traffic is already cut. Reconnect the VPN to keep it open.",
        ["Grace_BodyClock"] = "Claude's traffic is already cut. Putting the clock back keeps it open.",
        ["Grace_Closing"] = "Closing Claude in",
        ["Grace_Back"] = "VPN is back. Claude stays open.",
        ["Grace_Fixed"] = "Fixed in time. Claude stays open.",
        ["Grace_StopNow"] = "Close Claude now",
        ["Set_Grace"] = "Seconds to fix it before Claude closes",
        ["Set_Grace_Sub"] = "Traffic is cut at the firewall the instant a rule breaks. This is only how long you get to put the tunnel back before the app itself is closed.",
        ["Set_GraceOverlay"] = "Show the on-top countdown warning",
        ["Set_Grace_Off"] = "Close at once",
        ["Setup_Title"] = "One-time setup",
        ["Setup_Sub"] = "Registers the clock switches and the firewall rule together, so Windows asks for approval once and never again. It runs by itself the first time the app starts.",
        ["Setup_Ready"] = "Done",
        ["Setup_Missing"] = "Not done yet",
        ["Setup_Partial"] = "Partly done",
        ["Setup_Run"] = "Set everything up",
        ["Setup_Again"] = "Set up again",
        ["Setup_Declined"] = "Setup was declined. The guard still stops Claude, it just asks for approval when it changes the clock.",
        ["Claude_Found"] = "Claude found",
        ["Claude_Missing"] = "Claude was not found on this computer",
        ["Nav_Buy"] = "Buy",
        ["Buy_Title"] = "Plans and prices",
        ["Buy_Hint"] = "Prices in toman, everything included. Pick a plan and we take it from there.",
        ["Buy_Toman"] = "toman",
        ["Buy_PerMonth"] = "per month",
        ["Buy_PerYear"] = "per year",
        ["Buy_PerSeat"] = "per person, per month",
        ["Buy_Popular"] = "Most picked",
        ["Buy_Order"] = "Order this",
        ["Buy_Loading"] = "Fetching today's prices…",
        ["Buy_Updated"] = "Priced on",
        ["Buy_Stale"] = "These prices are a little old. Refresh before you rely on them.",
        ["Buy_Cached"] = "Saved prices, shown because the server could not be reached. They may have moved.",
        ["Buy_NoServer"] = "No order server is set. Add its address in Settings and the prices will appear here.",
        ["Buy_NoRate"] = "Prices are being set up. Try again shortly.",
        ["Buy_Unreachable"] = "Could not reach the server. Check your connection and try again.",
        ["Buy_Small"] = "A price holds for the day it was quoted. The rate moves, so the final amount is confirmed when your order is.",
        ["Nav_Orders"] = "Orders",
        ["Nav_Usage"] = "Usage",

        ["Ip_Title"] = "Your address",
        ["Ip_Checking"] = "Checking…",
        ["Ip_Failed"] = "The address could not be read",
        ["Ip_Leak"] = "Leak: this is the address you have without the tunnel",
        ["Ip_Copy"] = "Copy",
        ["Ip_Copied"] = "Copied",
        ["Ip_Source"] = "via",
        ["Ip_Home"] = "Address without the tunnel",

        ["Set_Firewall"] = "Block Claude's traffic at the firewall",
        ["Set_Firewall_Sub"] = "Stopping a process leaves a gap. A firewall rule refuses Claude's outbound traffic the moment a rule breaks, and lifts again when it is safe. Windows asks for approval once during setup.",
        ["Set_Firewall_On"] = "Ready",
        ["Set_Firewall_Off"] = "Not set up",
        ["Fw_Blocked"] = "Traffic blocked",
        ["Fw_Open"] = "Traffic allowed",
        ["Fw_Unknown"] = "Firewall state unknown",
        ["Fw_NoClaude"] = "Set the Claude program in Settings first.",

        ["Usage_Title"] = "Token usage",
        ["Usage_NeedKey"] = "Add an Anthropic admin key in Settings to read your usage.",
        ["Usage_KeyHint"] = "An admin key starts with sk-ant-admin and belongs to an API organisation. A Pro or Max subscription has no usage endpoint, so nothing can be read for those.",
        ["Usage_Days"] = "Period",
        ["Usage_Total"] = "Total tokens",
        ["Usage_Input"] = "Input",
        ["Usage_Output"] = "Output",
        ["Usage_Cost"] = "Cost",
        ["Usage_ByModel"] = "By model",
        ["Usage_Empty"] = "Nothing was used in this period.",
        ["Usage_Loading"] = "Reading…",
        ["Usage_Updated"] = "Read at",
        ["Usage_Err_no_key"] = "No admin key is set.",
        ["Usage_Err_unauthorized"] = "The key was refused.",
        ["Usage_Err_not_admin_key"] = "That key is not an admin key.",
        ["Usage_Err_rate_limited"] = "Too many requests. Try again shortly.",
        ["Usage_Err_network"] = "The API could not be reached.",

        ["Ord_Title"] = "Order a subscription",
        ["Ord_NoServer"] = "No order service is set. Add its address in Settings.",
        ["Ord_Server"] = "Order service address",
        ["Ord_Plan"] = "Plan",
        ["Ord_Months"] = "Duration",
        ["Ord_Email"] = "Claude account email",
        ["Ord_Contact"] = "Handle or number",
        ["Ord_ContactKind"] = "Reach me on",
        ["Ord_Country"] = "Country of use",
        ["Ord_Note"] = "Note (optional)",
        ["Ord_Eligible"] = "I confirm my account is used in a country Anthropic supports.",
        ["Ord_PasswordWarning"] = "Never send your account password. Paying never needs it.",
        ["Ord_Submit"] = "Place order",
        ["Ord_Sending"] = "Sending…",
        ["Ord_Done"] = "Order received",
        ["Ord_Keep"] = "Keep this code. You can check the status with it any time.",
        ["Ord_Again"] = "Place another order",
        ["Ord_Track"] = "Track an order",
        ["Ord_TrackBtn"] = "Track",
        ["Ord_Months1"] = "1 month",
        ["Ord_Months3"] = "3 months",
        ["Ord_Months6"] = "6 months",
        ["Ord_Months12"] = "12 months",
        ["Ord_St_New"] = "Received",
        ["Ord_St_Confirmed"] = "Confirmed",
        ["Ord_St_AwaitingPayment"] = "Awaiting payment",
        ["Ord_St_Paid"] = "Paid",
        ["Ord_St_Done"] = "Done",
        ["Ord_St_Cancelled"] = "Cancelled",
        ["Ord_Err_no_server"] = "No order service is set.",
        ["Ord_Err_network"] = "The service could not be reached.",
        ["Ord_Err_timeout"] = "The service did not answer in time.",
        ["Ord_Err_bad_email"] = "That email does not look right.",
        ["Ord_Err_bad_contact"] = "That contact does not look right.",
        ["Ord_Err_unknown_plan"] = "That plan is not available.",
        ["Ord_Err_eligibility_required"] = "Please tick the confirmation.",
        ["Ord_Err_too_many"] = "Too many requests. Try again later.",
        ["Ord_Err_not_found"] = "No order with that code.",
        ["Ord_Err_failed"] = "It did not go through."
    };

    private static readonly Dictionary<string, string> Fa = new()
    {
        ["App_Name"] = "Claude Watch",
        ["App_Tagline"] = "نگهبان VPN و ساعت",

        ["Nav_Dashboard"] = "وضعیت",
        ["Nav_Processes"] = "پردازش‌ها",
        ["Nav_Network"] = "شبکه",
        ["Nav_Activity"] = "رویدادها",
        ["Nav_Settings"] = "تنظیمات",
        ["Nav_About"] = "درباره",

        ["Head_Ready"] = "محافظت برقرار",
        ["Head_Blocked"] = "مسدود",
        ["Head_Standby"] = "آماده‌باش",
        ["Head_Mismatch"] = "ساعت ناهماهنگ",
        ["Head_Paused"] = "موقتاً متوقف",
        ["Head_Off"] = "نگهبان خاموش",

        ["Msg_Ready"] = "VPN وصل است و ساعت درست تنظیم شده. کلاد می‌تواند اجرا شود.",
        ["Msg_Blocked"] = "هیچ VPN فعالی پیدا نشد. کلاد بسته می‌ماند.",
        ["Msg_Standby"] = "ساعت ایران برگشت. پیش از باز کردن کلاد، ساعت کاری را آماده کنید.",
        ["Msg_Mismatch"] = "ساعت سیستم با منطقه‌ای که این حالت لازم دارد یکی نیست.",
        ["Msg_Paused"] = "همه قانون‌ها موقتاً متوقف‌اند. چیزی بسته نمی‌شود.",
        ["Msg_Off"] = "هر دو قانون در تنظیمات خاموش‌اند.",

        ["Tile_Vpn"] = "VPN",
        ["Tile_Clock"] = "ساعت سیستم",
        ["Tile_Claude"] = "کلاد",
        ["Vpn_None"] = "وصل نیست",
        ["Clock_Target"] = "لازم",
        ["Clock_Home"] = "خانه",
        ["Clock_Work"] = "کاری",
        ["Clock_Matches"] = "هماهنگ",
        ["Claude_None"] = "اجرا نمی‌شود",
        ["Claude_Running"] = "در حال اجرا",

        ["Btn_Open"] = "باز کردن کلاد",
        ["Btn_Stop"] = "بستن کلاد",
        ["Btn_Prepare"] = "آماده‌سازی ساعت کاری",
        ["Btn_HoldHome"] = "برگشت به ساعت ایران",
        ["Btn_Pause"] = "توقف موقت نگهبان",
        ["Btn_Resume"] = "ادامه نگهبانی",
        ["Btn_ChangeNow"] = "تغییر ساعت",
        ["Btn_SkipSession"] = "نادیده گرفتن قانون ساعت",
        ["Btn_RestoreRules"] = "برگرداندن قانون ساعت",
        ["Btn_Refresh"] = "به‌روزرسانی",
        ["Btn_Save"] = "ذخیره تغییرات",
        ["Btn_Saved"] = "ذخیره شد",
        ["Btn_Reset"] = "بازگشت به پیش‌فرض",
        ["Btn_Export"] = "خروجی",
        ["Btn_Clear"] = "پاک کردن",
        ["Btn_Browse"] = "انتخاب فایل",
        ["Btn_Install"] = "راه‌اندازی",
        ["Btn_Remove"] = "حذف",
        ["Btn_Trust"] = "مطمئن",
        ["Btn_Untrust"] = "لغو اطمینان",
        ["Btn_Ignore"] = "نادیده بگیر",
        ["Btn_Unignore"] = "دوباره حساب کن",
        ["Btn_StopOne"] = "بستن",
        ["Btn_Close"] = "بستن",
        ["Btn_Minimize"] = "کوچک کردن",

        ["Banner_ClockNeeded"] = "ساعت باید تغییر کند",
        ["Banner_ClockDetail"] = "ویندوز یک بار تأیید می‌خواهد و بعد کار ادامه پیدا می‌کند.",
        ["Banner_Failed"] = "تغییر آخر انجام نشد. کلاد مسدود می‌ماند.",
        ["Banner_Paused"] = "نگهبان متوقف است تا",

        ["Pause_15"] = "۱۵ دقیقه",
        ["Pause_30"] = "۳۰ دقیقه",
        ["Pause_60"] = "۱ ساعت",

        ["Proc_Title"] = "پردازش‌های منطبق",
        ["Proc_Empty"] = "چیزی در حال اجرا نیست.",
        ["Proc_Pid"] = "شناسه",
        ["Proc_Memory"] = "حافظه",
        ["Proc_Started"] = "شروع",
        ["Proc_StopAll"] = "بستن همه",
        ["Proc_Hint"] = "تشخیص فقط از روی نام برنامه است، پس اسکریپتی که اسم کلاد در آن آمده هرگز بسته نمی‌شود.",

        ["Net_Title"] = "کارت‌های شبکه",
        ["Net_Hint"] = "سبز یعنی این کارت الان به‌عنوان VPN حساب می‌شود. با «مطمئن» آن را ثابت کنید و با «نادیده بگیر» از فهرست بیرون بگذارید.",
        ["Net_Counts"] = "به‌عنوان VPN",
        ["Net_Up"] = "فعال",
        ["Net_Down"] = "غیرفعال",
        ["Net_Trusted"] = "مطمئن",
        ["Net_Ignored"] = "نادیده",
        ["Net_Idle"] = "بدون ترافیک",
        ["Net_Empty"] = "کارت شبکه‌ای پیدا نشد.",

        ["Act_Title"] = "رویدادها",
        ["Act_Empty"] = "هنوز اتفاقی نیفتاده.",
        ["Act_Hint"] = "نگهداری تا",
        ["Act_Days"] = "روز",

        ["Set_Protection"] = "محافظت",
        ["Set_EnforceVpn"] = "الزام اتصال VPN",
        ["Set_EnforceVpn_Sub"] = "به‌محض قطع شدن تونل، کلاد بسته می‌شود.",
        ["Set_EnforceTz"] = "الزام ساعت کاری",
        ["Set_EnforceTz_Sub"] = "تا وقتی کلاد باز است، ساعت سیستم روی منطقه زیر می‌ماند.",
        ["Set_Action"] = "وقتی قانونی نقض شود",
        ["Set_Action_Stop"] = "کلاد را ببند",
        ["Set_Action_Warn"] = "فقط هشدار بده",
        ["Set_Tolerance"] = "قطعی کوتاه VPN را نادیده بگیر تا",
        ["Set_Tolerance_Sub"] = "کلاد در هر حالت بلافاصله مسدود می‌شود؛ این فقط تغییر ساعت را عقب می‌اندازد.",
        ["Set_Checks"] = "بررسی",
        ["Set_Interval"] = "بررسی هر",
        ["Set_Seconds"] = "ثانیه",

        ["Set_Zones"] = "منطقه‌های زمانی",
        ["Set_WorkZone"] = "منطقه کاری (VPN وصل)",
        ["Set_HomeZone"] = "منطقه خانه (VPN قطع)",
        ["Set_TzMode"] = "تغییر ساعت",
        ["Set_TzMode_Ask"] = "اول از من بپرس",
        ["Set_TzMode_Auto"] = "خودکار تغییر بده",
        ["Set_TzMode_Report"] = "هرگز تغییر نده",
        ["Set_Helper"] = "حذف پنجره تأیید ویندوز",
        ["Set_Helper_Sub"] = "دو کار زمان‌بندی‌شده می‌سازد که ساعت را با دسترسی مدیر عوض می‌کنند. ویندوز فقط همین یک بار تأیید می‌خواهد.",
        ["Set_Helper_On"] = "آماده است",
        ["Set_Helper_Off"] = "راه‌اندازی نشده",

        ["Set_Detection"] = "تشخیص",
        ["Set_VpnPattern"] = "الگوی نام کارت VPN",
        ["Set_ProcPattern"] = "الگوی نام پردازش کلاد",
        ["Set_Extra"] = "این‌ها هم کلاد حساب شوند",
        ["Set_Excluded"] = "این‌ها هرگز بسته نشوند",
        ["Set_CommaHint"] = "نام‌ها را با ویرگول جدا کنید.",
        ["Set_Tunnels"] = "هر کارت تونل یا dial-up را VPN حساب کن",
        ["Set_Routed"] = "تونل فقط وقتی حساب شود که ترافیک از آن رد شود",
        ["Set_Routed_Sub"] = "تیل‌اسکیل و زیروتیر و مشابهشان تمام روز وصل می‌مانند تا به دستگاه‌های دیگر برسند، بدون اینکه ترافیک اینترنت شما را جابه‌جا کنند. با روشن بودن این گزینه، تونلی که ترافیک شما از آن عبور نمی‌کند محافظت حساب نمی‌شود. کارتی که خودتان مطمئن علامت زده‌اید در هر حال حساب می‌شود.",
        ["Set_BadPattern"] = "این الگو معتبر نیست.",

        ["Set_App"] = "برنامه",
        ["Set_Startup"] = "اجرا با ویندوز",
        ["Set_StartMin"] = "اجرای پنهان در نوار وظیفه",
        ["Set_MinTray"] = "کوچک شدن به نوار وظیفه",
        ["Set_CloseTray"] = "با بستن پنجره، اجرا ادامه پیدا کند",
        ["Set_Notify"] = "نمایش اعلان‌ها",
        ["Set_NotifyProblems"] = "فقط برای مشکل‌ها",
        ["Set_Sound"] = "پخش صدا همراه هشدار",
        ["Set_Confirm"] = "پیش از بستن دستی کلاد بپرس",
        ["Set_Hotkey"] = "کلید Ctrl+Alt+K کلاد را می‌بندد",
        ["Set_ClaudePath"] = "مسیر برنامه کلاد",
        ["Set_ClaudePath_Auto"] = "خودکار پیدا شد",
        ["Set_ClaudePath_Missing"] = "پیدا نشد — دستی انتخاب کنید",

        ["Set_Look"] = "ظاهر",
        ["Set_Theme"] = "پوسته",
        ["Set_Theme_Dark"] = "تیره",
        ["Set_Theme_Light"] = "روشن",
        ["Set_Theme_System"] = "مثل ویندوز",
        ["Set_Accent"] = "رنگ اصلی",
        ["Set_Language"] = "زبان",

        ["Set_Advanced"] = "نگهداری",
        ["Set_Retention"] = "نگهداری رویدادها برای",
        ["Set_DataFolder"] = "باز کردن پوشه داده‌ها",
        ["Set_ResetHint"] = "همه تنظیم‌ها به حالت اول برمی‌گردند.",

        ["About_What"] = "این برنامه چه می‌کند",
        ["About_Body"] = "تا وقتی برنامه کلاد باز است، Claude Watch دو شرط را نگه می‌دارد: تونل VPN برقرار باشد و ساعت سیستم روی منطقه کاری بماند. با شکستن هر کدام، همه پردازش‌های کلاد بسته می‌شوند و ساعت به منطقه خانه برمی‌گردد.",
        ["About_Warning"] = "این برنامه پردازش می‌بندد و ساعت سیستم را عوض می‌کند. هر دو عمدی است. تغییر ساعت به تأیید ویندوز نیاز دارد، مگر میان‌بر تنظیمات را راه بیندازید.",
        ["About_Credit"] = "بر پایه اسکریپت claude-watch از omidkorat.",
        ["About_Version"] = "نسخه",
        ["About_Source"] = "اسکریپت اصلی",
        ["About_Admin"] = "اجرا با دسترسی مدیر",
        ["About_NotAdmin"] = "اجرا با کاربر عادی",

        ["Tray_Open"] = "باز کردن Claude Watch",
        ["Tray_Stop"] = "همین حالا کلاد را ببند",
        ["Tray_Pause"] = "توقف ۳۰ دقیقه‌ای",
        ["Tray_Resume"] = "ادامه نگهبانی",
        ["Tray_Exit"] = "خروج",
        ["Tray_Running"] = "Claude Watch در نوار وظیفه باز است.",

        ["Confirm_Stop"] = "همه پردازش‌های کلاد بسته شوند؟",
        ["Confirm_Title"] = "Claude Watch",
        ["Confirm_Reset"] = "همه تنظیم‌ها به پیش‌فرض برگردند؟",

        ["Notify_Stopped"] = "کلاد بسته شد",
        ["Notify_VpnLost"] = "VPN قطع شد",
        ["Notify_VpnBack"] = "VPN برگشت",
        ["Notify_ClockChanged"] = "ساعت عوض شد",

        ["Grace_Vpn"] = "VPN قطع شد",
        ["Grace_Clock"] = "ساعت درست نیست",
        ["Grace_Body"] = "ترافیک کلاد همین الان قطع شد. VPN را وصل کنید تا باز بماند.",
        ["Grace_BodyClock"] = "ترافیک کلاد همین الان قطع شد. با برگرداندن ساعت باز می‌ماند.",
        ["Grace_Closing"] = "بسته شدن کلاد تا",
        ["Grace_Back"] = "VPN برگشت. کلاد باز می‌ماند.",
        ["Grace_Fixed"] = "به‌موقع درست شد. کلاد باز می‌ماند.",
        ["Grace_StopNow"] = "همین حالا ببند",
        ["Set_Grace"] = "ثانیه فرصت تا بسته شدن کلاد",
        ["Set_Grace_Sub"] = "همان لحظه که قانونی نقض شود ترافیک با فایروال قطع می‌شود. این عدد فقط فرصت شماست که تونل را برگردانید تا خود برنامه بسته نشود.",
        ["Set_GraceOverlay"] = "نمایش هشدار شمارش معکوس روی همه پنجره‌ها",
        ["Set_Grace_Off"] = "بدون مهلت",
        ["Setup_Title"] = "راه‌اندازی یک‌باره",
        ["Setup_Sub"] = "کلیدهای ساعت و قانون فایروال را با هم ثبت می‌کند تا ویندوز فقط یک بار تأیید بخواهد و دیگر هرگز نپرسد. بار اول که اپ باز شود خودش اجرا می‌شود.",
        ["Setup_Ready"] = "انجام شد",
        ["Setup_Missing"] = "هنوز انجام نشده",
        ["Setup_Partial"] = "ناقص انجام شده",
        ["Setup_Run"] = "راه‌اندازی همه",
        ["Setup_Again"] = "راه‌اندازی دوباره",
        ["Setup_Declined"] = "تأیید داده نشد. نگهبان همچنان کلاد را می‌بندد، فقط موقع تغییر ساعت تأیید می‌خواهد.",
        ["Claude_Found"] = "کلاد پیدا شد",
        ["Claude_Missing"] = "کلاد روی این کامپیوتر پیدا نشد",
        ["Nav_Buy"] = "خرید",
        ["Buy_Title"] = "پلن‌ها و قیمت‌ها",
        ["Buy_Hint"] = "قیمت‌ها به تومان و با همه‌چیز. پلن را انتخاب کنید، بقیه‌اش با ما.",
        ["Buy_Toman"] = "تومان",
        ["Buy_PerMonth"] = "ماهانه",
        ["Buy_PerYear"] = "سالانه",
        ["Buy_PerSeat"] = "هر نفر، ماهانه",
        ["Buy_Popular"] = "بیشترین انتخاب",
        ["Buy_Order"] = "همین را می‌خواهم",
        ["Buy_Loading"] = "در حال گرفتن قیمت امروز…",
        ["Buy_Updated"] = "قیمت‌گذاری",
        ["Buy_Stale"] = "این قیمت‌ها کمی قدیمی‌اند. قبل از تصمیم، به‌روزرسانی کنید.",
        ["Buy_Cached"] = "قیمت‌های ذخیره‌شده، چون سرور در دسترس نبود. ممکن است عوض شده باشند.",
        ["Buy_NoServer"] = "آدرس سرور سفارش وارد نشده. در تنظیمات واردش کنید تا قیمت‌ها اینجا بیایند.",
        ["Buy_NoRate"] = "قیمت‌ها هنوز آماده نیستند. کمی بعد دوباره امتحان کنید.",
        ["Buy_Unreachable"] = "سرور در دسترس نبود. اتصالتان را ببینید و دوباره امتحان کنید.",
        ["Buy_Small"] = "هر قیمت برای همان روز است. نرخ بالا و پایین می‌رود، پس مبلغ نهایی موقع تأیید سفارش قطعی می‌شود.",
        ["Nav_Orders"] = "سفارش",
        ["Nav_Usage"] = "مصرف",

        ["Ip_Title"] = "آدرس شما",
        ["Ip_Checking"] = "در حال بررسی…",
        ["Ip_Failed"] = "آدرس خوانده نشد",
        ["Ip_Leak"] = "نشتی: این همان آدرسی است که بدون تونل داری",
        ["Ip_Copy"] = "کپی",
        ["Ip_Copied"] = "کپی شد",
        ["Ip_Source"] = "از",
        ["Ip_Home"] = "آدرس بدون تونل",

        ["Set_Firewall"] = "بستن ترافیک کلاد با فایروال",
        ["Set_Firewall_Sub"] = "بستن پروسه یک فاصله زمانی کوتاه دارد. قانون فایروال همان لحظه که قانونی نقض شود جلوی ترافیک خروجی کلاد را می‌گیرد و وقتی شرایط امن شد کنار می‌رود. ویندوز فقط موقع راه‌اندازی یک بار تأیید می‌خواهد.",
        ["Set_Firewall_On"] = "آماده",
        ["Set_Firewall_Off"] = "راه‌اندازی نشده",
        ["Fw_Blocked"] = "ترافیک بسته است",
        ["Fw_Open"] = "ترافیک باز است",
        ["Fw_Unknown"] = "وضعیت فایروال نامشخص",
        ["Fw_NoClaude"] = "اول مسیر برنامه کلاد را در تنظیمات مشخص کنید.",

        ["Usage_Title"] = "مصرف توکن",
        ["Usage_NeedKey"] = "برای دیدن مصرف، کلید ادمین Anthropic را در تنظیمات وارد کنید.",
        ["Usage_KeyHint"] = "کلید ادمین با sk-ant-admin شروع می‌شود و مال یک سازمان API است. اشتراک Pro و Max اندپوینت مصرف ندارند و برای آن‌ها چیزی خوانده نمی‌شود.",
        ["Usage_Days"] = "بازه",
        ["Usage_Total"] = "کل توکن",
        ["Usage_Input"] = "ورودی",
        ["Usage_Output"] = "خروجی",
        ["Usage_Cost"] = "هزینه",
        ["Usage_ByModel"] = "به تفکیک مدل",
        ["Usage_Empty"] = "در این بازه مصرفی ثبت نشده.",
        ["Usage_Loading"] = "در حال خواندن…",
        ["Usage_Updated"] = "خوانده شده در",
        ["Usage_Err_no_key"] = "کلید ادمین وارد نشده.",
        ["Usage_Err_unauthorized"] = "کلید پذیرفته نشد.",
        ["Usage_Err_not_admin_key"] = "این کلید، کلید ادمین نیست.",
        ["Usage_Err_rate_limited"] = "درخواست زیاد بود. کمی بعد دوباره امتحان کنید.",
        ["Usage_Err_network"] = "ارتباط با API برقرار نشد.",

        ["Ord_Title"] = "سفارش اشتراک",
        ["Ord_NoServer"] = "سرویس سفارش تنظیم نشده. آدرسش را در تنظیمات وارد کنید.",
        ["Ord_Server"] = "آدرس سرویس سفارش",
        ["Ord_Plan"] = "اشتراک",
        ["Ord_Months"] = "مدت",
        ["Ord_Email"] = "ایمیل اکانت Claude",
        ["Ord_Contact"] = "آیدی یا شماره",
        ["Ord_ContactKind"] = "راه ارتباطی",
        ["Ord_Country"] = "کشور محل استفاده",
        ["Ord_Note"] = "توضیح (اختیاری)",
        ["Ord_Eligible"] = "تأیید می‌کنم اکانتم در کشوری استفاده می‌شود که Anthropic پشتیبانی می‌کند.",
        ["Ord_PasswordWarning"] = "رمز اکانت را هرگز نفرستید. برای پرداخت لازم نیست.",
        ["Ord_Submit"] = "ثبت سفارش",
        ["Ord_Sending"] = "در حال ارسال…",
        ["Ord_Done"] = "سفارش ثبت شد",
        ["Ord_Keep"] = "این کد را نگه دارید. هر وقت خواستید با آن وضعیت را ببینید.",
        ["Ord_Again"] = "ثبت سفارش دیگر",
        ["Ord_Track"] = "پیگیری سفارش",
        ["Ord_TrackBtn"] = "پیگیری",
        ["Ord_Months1"] = "۱ ماه",
        ["Ord_Months3"] = "۳ ماه",
        ["Ord_Months6"] = "۶ ماه",
        ["Ord_Months12"] = "۱۲ ماه",
        ["Ord_St_New"] = "ثبت شده",
        ["Ord_St_Confirmed"] = "تأیید شده",
        ["Ord_St_AwaitingPayment"] = "در انتظار تسویه",
        ["Ord_St_Paid"] = "پرداخت شد",
        ["Ord_St_Done"] = "انجام شد",
        ["Ord_St_Cancelled"] = "لغو شد",
        ["Ord_Err_no_server"] = "سرویس سفارش تنظیم نشده.",
        ["Ord_Err_network"] = "ارتباط با سرویس برقرار نشد.",
        ["Ord_Err_timeout"] = "سرویس به‌موقع جواب نداد.",
        ["Ord_Err_bad_email"] = "ایمیل درست وارد نشده.",
        ["Ord_Err_bad_contact"] = "راه ارتباطی درست وارد نشده.",
        ["Ord_Err_unknown_plan"] = "این اشتراک در دسترس نیست.",
        ["Ord_Err_eligibility_required"] = "باید تیک تأیید را بزنید.",
        ["Ord_Err_too_many"] = "درخواست زیاد بود. بعداً دوباره تلاش کنید.",
        ["Ord_Err_not_found"] = "سفارشی با این کد پیدا نشد.",
        ["Ord_Err_failed"] = "ثبت نشد."
    };
}
