using System;
using System.Collections.Generic;

namespace ClaudeWatch.App;

/// <summary>
/// Every visible word in one place, in English and Persian. Bindings go through
/// the indexer (<c>{Binding L[Nav_Dashboard]}</c>), so switching language is a
/// single property change on the view model.
/// </summary>
public sealed class Strings
{
    private string _language = "en";

    public string Language
    {
        get => _language;
        set => _language = value == "fa" ? "fa" : "en";
    }

    public bool IsRightToLeft => _language == "fa";

    /// <summary>
    /// The service the window is showing. Every string containing {app} is
    /// rewritten with it, so "Stop Claude" reads "Stop ChatGPT" the moment the
    /// toggle moves, with one table rather than two.
    /// </summary>
    public string ServiceName { get; set; } = "Claude";

    public string this[string key]
    {
        get
        {
            var table = _language == "fa" ? Fa : En;

            if (table.TryGetValue(key, out var value))
            {
                return Fill(value);
            }

            return En.TryGetValue(key, out var fallback) ? Fill(fallback) : key;
        }
    }

    public string Get(string key) => this[key];

    private string Fill(string text)
        => text.Contains("{app}", StringComparison.Ordinal)
            ? text.Replace("{app}", ServiceName, StringComparison.Ordinal)
            : text;

    private static readonly Dictionary<string, string> En = new()
    {
        ["App_Name"] = "SafeChat",
        ["Head_Locked"] = "Not activated",
        ["Msg_Locked"] = "The trial has ended. Enter a key and protection starts again.",

        ["Lock_Title"] = "Protection is off",
        ["Lock_Body"] = "The controls below need an active key. Buying and ordering keep working without one.",
        ["Lock_Action"] = "Enter a key",
        ["Lock_Why"] = "Needs an active key",
        ["Lock_TrialLeft"] = "days of trial left",
        ["Bar_Device"] = "This computer",
        ["Svc_RuleVpn"] = "VPN required",
        ["Svc_RuleClock"] = "clock enforced",
        ["Svc_RuleFirewall"] = "kill switch on",
        ["Svc_RuleNone"] = "nothing is being enforced",

        ["Nav_Licence"] = "Activation",
        ["Lic_Title"] = "Activation",
        ["Lic_Hint"] = "One key, one computer. Buying and ordering work without it; protection does not.",
        ["Lic_Key"] = "Your key",
        ["Lic_Activate"] = "Activate",
        ["Lic_Checking"] = "Checking…",
        ["Lic_Trial"] = "Trial",
        ["Lic_TrialLeft"] = "days of trial left",
        ["Lic_Active"] = "Active",
        ["Lic_DaysLeft"] = "days left",
        ["Lic_Until"] = "Runs until",
        ["Lic_NeedsKey"] = "The trial has ended. Protection is off until a key is activated.",
        ["Lic_Expired"] = "This key has run out. Renew it and activate again.",
        ["Lic_WrongDevice"] = "This key is already in use on another computer.",
        ["Lic_Revoked"] = "This key was switched off.",
        ["Lic_Offline"] = "The server could not be reached. Protection keeps running until the key's own end date.",
        ["Lic_Unknown"] = "This key was not recognised. Check it and try again.",
        ["Lic_NoServer"] = "No server address is set. Add it in Settings first.",
        ["Lic_Buy"] = "I do not have a key",

        ["Svc_Claude"] = "Claude",
        ["Svc_ChatGpt"] = "ChatGPT",
        ["Svc_Switch"] = "Switch service",
        ["Svc_Enabled"] = "Watch this app",
        ["Svc_Both"] = "Both apps are watched. The clock rule follows the one you have selected.",

        ["Wiz_Welcome"] = "Welcome to SafeChat",
        ["Wiz_Intro"] = "A few quick questions and you are done. Everything here can be changed later.",
        ["Wiz_Lang"] = "Which language?",
        ["Wiz_Apps"] = "Which apps do you use?",
        ["Wiz_Apps_Sub"] = "Only the ones you tick are watched.",
        ["Wiz_Zone"] = "Which time zone should your session look like?",
        ["Wiz_Zone_Sub"] = "The clock is put back to your home zone the moment the tunnel drops.",
        ["Wiz_Key"] = "Have a key?",
        ["Wiz_Key_Sub"] = "Leave it empty to start the trial. You can activate any time.",
        ["Wiz_Server"] = "Server address",
        ["Wiz_Server_Sub"] = "Where orders and keys are checked. Already filled in — change it only if you were given a different address.",
        ["Wiz_Next"] = "Next",
        ["Wiz_Back"] = "Back",
        ["Wiz_Finish"] = "Finish",
        ["Wiz_Skip"] = "Skip for now",
        ["App_Tagline"] = "VPN and clock guard",

        ["Nav_Dashboard"] = "Dashboard",
        ["Nav_Processes"] = "Processes",
        ["Nav_Network"] = "Network",
        ["Nav_Activity"] = "Activity",
        ["Nav_Settings"] = "Settings",
        ["Nav_About"] = "About",

        ["Head_Ready"] = "Protected",
        ["Head_Blocked"] = "Blocked",
        ["Head_Standby"] = "Standby",
        ["Head_Mismatch"] = "Clock mismatch",
        ["Head_Paused"] = "Paused",
        ["Head_Off"] = "Guard off",

        ["Msg_Ready"] = "VPN is up and the clock matches. {app} is free to run.",
        ["Msg_Blocked"] = "No VPN detected. {app} is stopped and stays stopped.",
        ["Msg_Standby"] = "Home time is back while {app} is closed. Prepare before you open it.",
        ["Msg_Mismatch"] = "The system clock is not the zone this session needs.",
        ["Msg_Paused"] = "All rules are paused. Nothing will be stopped.",
        ["Msg_Off"] = "Both rules are switched off in Settings.",

        ["Tile_Vpn"] = "VPN",
        ["Tile_Clock"] = "System clock",
        ["Tile_Claude"] = "{app}",
        ["Vpn_None"] = "Not connected",
        ["Clock_Target"] = "Needs",
        ["Clock_Home"] = "Home",
        ["Clock_Work"] = "Work",
        ["Clock_Matches"] = "Matches",
        ["Claude_None"] = "Not running",
        ["Claude_Running"] = "running",

        ["Btn_Open"] = "Open {app}",
        ["Btn_Stop"] = "Stop {app}",
        ["Btn_Prepare"] = "Prepare work time",
        ["Btn_HoldHome"] = "Back to home time",
        ["Btn_Pause"] = "Pause guard",
        ["Btn_Resume"] = "Resume guard",
        ["Btn_ChangeNow"] = "Change the clock",
        ["Btn_SkipSession"] = "Skip clock rules",
        ["Btn_RestoreRules"] = "Restore clock rules",
        ["Btn_Refresh"] = "Refresh",
        ["Btn_Save"] = "Save changes",
        ["Btn_Saved"] = "Saved",
        ["Btn_Reset"] = "Reset to defaults",
        ["Btn_Export"] = "Export",
        ["Btn_Clear"] = "Clear",
        ["Btn_Browse"] = "Browse",
        ["Btn_Install"] = "Set up now",
        ["Btn_Remove"] = "Remove",
        ["Btn_Trust"] = "Trust",
        ["Btn_Untrust"] = "Untrust",
        ["Btn_Ignore"] = "Ignore",
        ["Btn_Unignore"] = "Stop ignoring",
        ["Btn_StopOne"] = "Stop",
        ["Btn_Close"] = "Close",
        ["Btn_Minimize"] = "Minimize",

        ["Banner_ClockNeeded"] = "The clock needs to change",
        ["Banner_ClockDetail"] = "Windows asks for approval once, then the guard continues.",
        ["Banner_Failed"] = "The last change did not go through. {app} stays blocked.",
        ["Banner_Paused"] = "Guard paused until",

        ["Pause_15"] = "15 minutes",
        ["Pause_30"] = "30 minutes",
        ["Pause_60"] = "1 hour",

        ["Proc_Title"] = "Matching processes",
        ["Proc_Empty"] = "Nothing matching is running.",
        ["Proc_Pid"] = "PID",
        ["Proc_Memory"] = "Memory",
        ["Proc_Started"] = "Started",
        ["Proc_StopAll"] = "Stop all",
        ["Proc_Hint"] = "Matching is on the program name only, so a script that merely mentions the app is never touched.",

        ["Net_Title"] = "Network adapters",
        ["Net_Hint"] = "Green means this adapter counts as your VPN right now. Trust one to force it, ignore one to rule it out.",
        ["Net_Counts"] = "Counts as VPN",
        ["Net_Up"] = "Up",
        ["Net_Down"] = "Down",
        ["Net_Trusted"] = "Trusted",
        ["Net_Ignored"] = "Ignored",
        ["Net_Idle"] = "No traffic",
        ["Net_Empty"] = "No adapters were found.",

        ["Act_Title"] = "Activity",
        ["Act_Empty"] = "Nothing has happened yet.",

        ["Today_Title"] = "Today",
        ["Today_Calm"] = "Nothing needed stopping today.",
        ["Today_Busy"] = "The guard stepped in today.",
        ["Today_Stops"] = "times {app} was stopped",
        ["Today_VpnDrops"] = "VPN drops",
        ["Today_TimeZone"] = "clock changes",
        ["Today_Blocks"] = "times traffic was cut",
        ["Today_Watching"] = "Watching since midnight.",
        ["Today_Last"] = "Last one at",
        ["Act_Hint"] = "Kept for",
        ["Act_Days"] = "days",

        ["Set_Protection"] = "Protection",
        ["Set_EnforceVpn"] = "Require a VPN",
        ["Set_EnforceVpn_Sub"] = "Stop the app the moment the tunnel drops.",
        ["Set_EnforceTz"] = "Require the work time zone",
        ["Set_EnforceTz_Sub"] = "Keep the system clock in the zone below while {app} runs.",
        ["Set_Action"] = "When a rule breaks",
        ["Set_Action_Stop"] = "Stop the app",
        ["Set_Action_Warn"] = "Only warn me",
        ["Set_Tolerance"] = "Ignore short VPN drops for",
        ["Set_Tolerance_Sub"] = "The app is blocked immediately either way; this only delays changing the clock.",
        ["Set_Checks"] = "checks",
        ["Set_Interval"] = "Check every",
        ["Set_Seconds"] = "seconds",

        ["Set_Zones"] = "Time zones",
        ["Set_WorkZone"] = "Work zone (VPN connected)",
        ["Set_HomeZone"] = "Home zone (VPN off)",
        ["Set_TzMode"] = "Changing the clock",
        ["Set_TzMode_Ask"] = "Ask me first",
        ["Set_TzMode_Auto"] = "Change it automatically",
        ["Set_TzMode_Report"] = "Never change it",
        ["Set_Helper"] = "Skip the approval prompt",
        ["Set_Helper_Sub"] = "Registers two scheduled tasks that switch the clock with administrator rights. Windows asks once during setup, then never again.",
        ["Set_Helper_On"] = "Set up",
        ["Set_Helper_Off"] = "Not set up",

        ["Set_Detection"] = "Detection",
        ["Set_VpnPattern"] = "VPN adapter pattern",
        ["Set_ProcPattern"] = "{app} process pattern",
        ["Set_Extra"] = "Also treat as {app}",
        ["Set_Excluded"] = "Never stop",
        ["Set_CommaHint"] = "Separate names with commas.",
        ["Set_Tunnels"] = "Count any tunnel or dial-up adapter as a VPN",
        ["Set_Routed"] = "Only count a tunnel while it carries your traffic",
        ["Set_Routed_Sub"] = "Tailscale, ZeroTier and the like stay connected all day to reach other machines without moving your browsing anywhere. With this on, a tunnel your traffic is not going through does not count as protection. An adapter you marked as trusted still counts either way.",
        ["Set_BadPattern"] = "That pattern is not valid.",

        ["Set_App"] = "Application",
        ["Set_Startup"] = "Start with Windows",
        ["Set_StartMin"] = "Start hidden in the tray",
        ["Set_MinTray"] = "Minimize to the tray",
        ["Set_CloseTray"] = "Keep running when the window closes",
        ["Set_Notify"] = "Show notifications",
        ["Set_NotifyProblems"] = "Only for problems",
        ["Set_Sound"] = "Play a sound with alerts",
        ["Set_Confirm"] = "Ask before I stop the app by hand",
        ["Set_Hotkey"] = "Ctrl+Alt+K stops the app from anywhere",
        ["Set_ClaudePath"] = "{app} program",
        ["Set_ClaudePath_Auto"] = "Found automatically",
        ["Set_ClaudePath_Missing"] = "Not found — pick it by hand",

        ["Set_Look"] = "Appearance",
        ["Set_Theme"] = "Theme",
        ["Set_Theme_Dark"] = "Dark",
        ["Set_Theme_Light"] = "Light",
        ["Set_Theme_System"] = "Follow Windows",
        ["Set_Accent"] = "Colour for {app}",
        ["Set_Language"] = "Language",

        ["Set_Advanced"] = "Housekeeping",
        ["Set_Retention"] = "Keep the activity log for",
        ["Set_DataFolder"] = "Open the data folder",
        ["Set_ResetHint"] = "Puts every setting back the way it started.",
        ["Set_Transfer"] = "Move these settings to another computer",
        ["Set_TransferHint"] = "Saves everything except the key, which belongs to this computer alone.",
        ["Set_Export"] = "Save to a file",
        ["Set_Import"] = "Load from a file",
        ["Set_ImportConfirm"] = "The settings in that file replace the ones here. Your key stays as it is.",

        ["About_What"] = "What this does",
        ["About_Body"] = "Claude Watch keeps two conditions true while the Claude desktop app is open: a VPN tunnel is up, and the system clock sits in your work zone. If either one breaks, every matching Claude process is stopped and the clock is put back to your home zone.",
        ["About_Warning"] = "This app stops processes and changes the system clock. Both are deliberate. Changing the clock needs Windows approval unless you set up the shortcut in Settings.",
        ["About_Version"] = "Version",
        ["About_Admin"] = "Running as administrator",
        ["About_NotAdmin"] = "Running as a normal user",

        ["Tray_Open"] = "Open Claude Watch",
        ["Tray_Stop"] = "Stop Claude now",
        ["Tray_Pause"] = "Pause for 30 minutes",
        ["Tray_Resume"] = "Resume the guard",
        ["Tray_Exit"] = "Quit",
        ["Tray_Running"] = "Claude Watch is still running in the tray.",

        ["Confirm_Stop"] = "Stop every running Claude process?",
        ["Confirm_Title"] = "SafeChat",
        ["Confirm_Reset"] = "Put every setting back to its default?",

        ["Notify_Stopped"] = "Claude was stopped",
        ["Notify_VpnLost"] = "VPN dropped",
        ["Notify_VpnBack"] = "VPN is back",
        ["Notify_ClockChanged"] = "Clock changed",

        ["Grace_Vpn"] = "VPN disconnected",
        ["Grace_Clock"] = "The clock is wrong",
        ["Grace_Body"] = "Claude's traffic is already cut. Reconnect the VPN to keep it open.",
        ["Grace_BodyClock"] = "Claude's traffic is already cut. Putting the clock back keeps it open.",
        ["Grace_Closing"] = "Closing Claude in",
        ["Grace_Back"] = "VPN is back. Claude stays open.",
        ["Grace_Fixed"] = "Fixed in time. Claude stays open.",
        ["Grace_StopNow"] = "Close Claude now",
        ["Set_Grace"] = "Seconds to fix it before Claude closes",
        ["Set_Grace_Sub"] = "Traffic is cut at the firewall the instant a rule breaks. This is only how long you get to put the tunnel back before the app itself is closed.",
        ["Set_GraceOverlay"] = "Show the on-top countdown warning",
        ["Set_Grace_Off"] = "Close at once",
        ["Setup_Title"] = "One-time setup",
        ["Setup_Sub"] = "Registers the clock switches and the firewall rule together, so Windows asks for approval once and never again. It runs by itself the first time the app starts.",
        ["Setup_Ready"] = "Done",
        ["Setup_Missing"] = "Not done yet",
        ["Setup_Partial"] = "Partly done",
        ["Setup_Run"] = "Set everything up",
        ["Setup_Again"] = "Set up again",
        ["Setup_Declined"] = "Setup was declined. The guard still stops Claude, it just asks for approval when it changes the clock.",
        ["Claude_Found"] = "Claude found",
        ["Claude_Missing"] = "Claude was not found on this computer",
        ["Nav_Buy"] = "Buy",
        ["Buy_Title"] = "Plans and prices",
        ["Buy_Hint"] = "Prices in toman, everything included. Pick a plan and we take it from there.",
        ["Buy_Toman"] = "toman",
        ["Buy_PerMonth"] = "per month",
        ["Buy_PerYear"] = "per year",
        ["Buy_PerSeat"] = "per person, per month",
        ["Buy_Popular"] = "Most picked",
        ["Buy_Order"] = "Order this",
        ["Buy_Loading"] = "Fetching today's prices…",
        ["Buy_Updated"] = "Priced on",
        ["Buy_Stale"] = "These prices are a little old. Refresh before you rely on them.",
        ["Buy_Cached"] = "Saved prices, shown because the server could not be reached. They may have moved.",
        ["Buy_NoServer"] = "No order server is set. Add its address in Settings and the prices will appear here.",
        ["Buy_NoRate"] = "Prices are being set up. Try again shortly.",
        ["Buy_Unreachable"] = "Could not reach the server. Check your connection and try again.",
        ["Buy_Small"] = "A price holds for the day it was quoted. The rate moves, so the final amount is confirmed when your order is.",
        ["Nav_Orders"] = "Orders",

        ["Ip_Title"] = "Your address",
        ["Ip_Checking"] = "Checking…",
        ["Ip_Failed"] = "The address could not be read",
        ["Ip_Leak"] = "Leak: this is the address you have without the tunnel",
        ["Ip_Copy"] = "Copy",
        ["Ip_Copied"] = "Copied",
        ["Ip_Source"] = "via",
        ["Ip_Home"] = "Address without the tunnel",

        ["Set_Firewall"] = "Block Claude's traffic at the firewall",
        ["Set_Firewall_Sub"] = "Stopping a process leaves a gap. A firewall rule refuses Claude's outbound traffic the moment a rule breaks, and lifts again when it is safe. Windows asks for approval once during setup.",
        ["Set_Firewall_On"] = "Ready",
        ["Set_Firewall_Off"] = "Not set up",
        ["Fw_Blocked"] = "Traffic blocked",
        ["Fw_Open"] = "Traffic allowed",
        ["Fw_Unknown"] = "Firewall state unknown",
        ["Fw_NoClaude"] = "Set the Claude program in Settings first.",


        ["Upd_Available"] = "SafeChat {0} is out",
        ["Upd_Size"] = "{0} MB",
        ["Upd_Downloading"] = "Downloading the new version",
        ["Upd_Checking"] = "Checking the download",
        ["Upd_Ready"] = "Ready to install",
        ["Upd_Installing"] = "Installing. SafeChat will close and open again.",
        ["Upd_Failed"] = "The update did not go through",
        ["Upd_Corrupt"] = "The file did not arrive whole, so it was thrown away. Try again.",
        ["Upd_NoReach"] = "Could not reach the server. Your settings and your key are untouched.",
        ["Upd_Looking"] = "Looking for a new version...",
        ["Upd_Current"] = "Version {0}, up to date",
        ["Upd_CurrentAt"] = "Version {0}, checked at {1}",
        ["Upd_Install"] = "Install",
        ["Upd_Later"] = "Not now",
        ["Upd_Check"] = "Check now",
        ["Upd_Auto"] = "Tell me when a new version is out",
        ["Upd_Auto_Sub"] = "Checks the server every few hours. It is offered and waits; nothing installs on its own.",
        ["Upd_Section"] = "Version",
        ["Upd_Logged"] = "Version {0} is available",
        ["Upd_Started"] = "Installing version {0}",
        ["Upd_Notes"] = "What changed",

        ["Ord_Title"] = "Order a subscription",
        ["Ord_NoServer"] = "No order service is set. Add its address in Settings.",
        ["Ord_Server"] = "Order service address",
        ["Ord_Plan"] = "Plan",
        ["Ord_Months"] = "Duration",
        ["Ord_Name"] = "Full name",
        ["Ord_Email"] = "Email of the account to activate",
        ["Ord_Contact"] = "Handle or number",
        ["Ord_ContactKind"] = "Reach me on",
        ["Ord_Country"] = "Country of use",
        ["Ord_Note"] = "Note (optional)",
        ["Ord_Eligible"] = "I confirm my account is used in a country Anthropic supports.",
        ["Ord_PasswordWarning"] = "Never send your account password. Paying never needs it.",
        ["Ord_Submit"] = "Place order",
        ["Ord_Sending"] = "Sending…",
        ["Ord_Done"] = "Order received",
        ["Ord_Keep"] = "Keep this code. You can check the status with it any time.",
        ["Ord_Again"] = "Place another order",
        ["Ord_Track"] = "Track an order",
        ["Ord_TrackBtn"] = "Track",
        ["Ord_Months1"] = "1 month",
        ["Ord_Months3"] = "3 months",
        ["Ord_Months6"] = "6 months",
        ["Ord_Months12"] = "12 months",
        ["Ord_St_New"] = "Received",
        ["Ord_St_Confirmed"] = "Confirmed",
        ["Ord_St_AwaitingPayment"] = "Awaiting payment",
        ["Ord_St_Paid"] = "Paid",
        ["Ord_St_Done"] = "Done",
        ["Ord_St_Cancelled"] = "Cancelled",
        ["Ord_Err_no_server"] = "No order service is set.",
        ["Ord_Err_network"] = "The service could not be reached.",
        ["Ord_Err_timeout"] = "The service did not answer in time.",
        ["Ord_Err_bad_email"] = "That email does not look right.",
        ["Ord_Err_bad_name"] = "Please put your full name in.",
        ["Ord_Err_bad_contact"] = "That contact does not look right.",
        ["Ord_Err_unknown_plan"] = "That plan is not available.",
        ["Ord_Err_eligibility_required"] = "Please tick the confirmation.",
        ["Ord_Err_too_many"] = "Too many requests. Try again later.",
        ["Ord_Err_not_found"] = "No order with that code.",
        ["Ord_Err_failed"] = "It did not go through."
    };

    private static readonly Dictionary<string, string> Fa = new()
    {
        ["App_Name"] = "SafeChat",
        ["Head_Locked"] = "فعال نشده",
        ["Msg_Locked"] = "دوره آزمایشی تمام شد. کلید را وارد کنید تا محافظت دوباره شروع شود.",

        ["Lock_Title"] = "محافظت خاموش است",
        ["Lock_Body"] = "دکمه‌های پایین به کلید فعال نیاز دارند. خرید و ثبت سفارش بدون کلید هم کار می‌کنند.",
        ["Lock_Action"] = "وارد کردن کلید",
        ["Lock_Why"] = "نیازمند کلید فعال",
        ["Lock_TrialLeft"] = "روز از دوره آزمایشی مانده",
        ["Bar_Device"] = "این کامپیوتر",
        ["Svc_RuleVpn"] = "وی‌پی‌ان لازم است",
        ["Svc_RuleClock"] = "ساعت کنترل می‌شود",
        ["Svc_RuleFirewall"] = "کیل‌سوییچ روشن",
        ["Svc_RuleNone"] = "هیچ قانونی اعمال نمی‌شود",

        ["Nav_Licence"] = "فعال‌سازی",
        ["Lic_Title"] = "فعال‌سازی",
        ["Lic_Hint"] = "هر کلید روی یک کامپیوتر. خرید و ثبت سفارش بدون کلید کار می‌کند، محافظت نه.",
        ["Lic_Key"] = "کلید شما",
        ["Lic_Activate"] = "فعال کن",
        ["Lic_Checking"] = "در حال بررسی…",
        ["Lic_Trial"] = "آزمایشی",
        ["Lic_TrialLeft"] = "روز از دوره آزمایشی مانده",
        ["Lic_Active"] = "فعال",
        ["Lic_DaysLeft"] = "روز مانده",
        ["Lic_Until"] = "تا تاریخ",
        ["Lic_NeedsKey"] = "دوره آزمایشی تمام شد. تا فعال شدن کلید، محافظت خاموش است.",
        ["Lic_Expired"] = "این کلید تمام شده. تمدیدش کنید و دوباره فعال کنید.",
        ["Lic_WrongDevice"] = "این کلید روی کامپیوتر دیگری فعال است.",
        ["Lic_Revoked"] = "این کلید غیرفعال شده.",
        ["Lic_Offline"] = "سرور در دسترس نبود. محافظت تا تاریخ پایان خودِ کلید ادامه دارد.",
        ["Lic_Unknown"] = "این کلید شناخته نشد. دوباره بررسی کنید.",
        ["Lic_NoServer"] = "آدرس سرور وارد نشده. اول در تنظیمات واردش کنید.",
        ["Lic_Buy"] = "کلید ندارم",

        ["Svc_Claude"] = "کلاد",
        ["Svc_ChatGpt"] = "چت‌جی‌پی‌تی",
        ["Svc_Switch"] = "تعویض سرویس",
        ["Svc_Enabled"] = "این اپ زیر نظر باشد",
        ["Svc_Both"] = "هر دو اپ زیر نظرند. قانون ساعت از سرویسی که انتخاب کرده‌اید پیروی می‌کند.",

        ["Wiz_Welcome"] = "به SafeChat خوش آمدید",
        ["Wiz_Intro"] = "چند سوال کوتاه و تمام. همه‌اش را بعداً هم می‌توانید عوض کنید.",
        ["Wiz_Lang"] = "زبان؟",
        ["Wiz_Apps"] = "از کدام اپ‌ها استفاده می‌کنید؟",
        ["Wiz_Apps_Sub"] = "فقط همان‌هایی که تیک بزنید زیر نظر گرفته می‌شوند.",
        ["Wiz_Zone"] = "جلسه شما باید شبیه کدام منطقه زمانی باشد؟",
        ["Wiz_Zone_Sub"] = "همان لحظه که تونل قطع شود ساعت به منطقه خانگی برمی‌گردد.",
        ["Wiz_Key"] = "کلید دارید؟",
        ["Wiz_Key_Sub"] = "خالی بگذارید تا دوره آزمایشی شروع شود. هر وقت خواستید فعال کنید.",
        ["Wiz_Server"] = "آدرس سرور",
        ["Wiz_Server_Sub"] = "جایی که سفارش و کلید بررسی می‌شود. از قبل پر شده و فقط اگر آدرس دیگری به شما داده‌اند عوضش کنید.",
        ["Wiz_Next"] = "بعدی",
        ["Wiz_Back"] = "قبلی",
        ["Wiz_Finish"] = "تمام",
        ["Wiz_Skip"] = "فعلاً رد کن",
        ["App_Tagline"] = "نگهبان VPN و ساعت",

        ["Nav_Dashboard"] = "وضعیت",
        ["Nav_Processes"] = "پردازش‌ها",
        ["Nav_Network"] = "شبکه",
        ["Nav_Activity"] = "رویدادها",
        ["Nav_Settings"] = "تنظیمات",
        ["Nav_About"] = "درباره",

        ["Head_Ready"] = "محافظت برقرار",
        ["Head_Blocked"] = "مسدود",
        ["Head_Standby"] = "آماده‌باش",
        ["Head_Mismatch"] = "ساعت ناهماهنگ",
        ["Head_Paused"] = "موقتاً متوقف",
        ["Head_Off"] = "نگهبان خاموش",

        ["Msg_Ready"] = "VPN وصل است و ساعت درست تنظیم شده. کلاد می‌تواند اجرا شود.",
        ["Msg_Blocked"] = "هیچ VPN فعالی پیدا نشد. کلاد بسته می‌ماند.",
        ["Msg_Standby"] = "ساعت ایران برگشت. پیش از باز کردن کلاد، ساعت کاری را آماده کنید.",
        ["Msg_Mismatch"] = "ساعت سیستم با منطقه‌ای که این حالت لازم دارد یکی نیست.",
        ["Msg_Paused"] = "همه قانون‌ها موقتاً متوقف‌اند. چیزی بسته نمی‌شود.",
        ["Msg_Off"] = "هر دو قانون در تنظیمات خاموش‌اند.",

        ["Tile_Vpn"] = "VPN",
        ["Tile_Clock"] = "ساعت سیستم",
        ["Tile_Claude"] = "کلاد",
        ["Vpn_None"] = "وصل نیست",
        ["Clock_Target"] = "لازم",
        ["Clock_Home"] = "خانه",
        ["Clock_Work"] = "کاری",
        ["Clock_Matches"] = "هماهنگ",
        ["Claude_None"] = "اجرا نمی‌شود",
        ["Claude_Running"] = "در حال اجرا",

        ["Btn_Open"] = "باز کردن کلاد",
        ["Btn_Stop"] = "بستن کلاد",
        ["Btn_Prepare"] = "آماده‌سازی ساعت کاری",
        ["Btn_HoldHome"] = "برگشت به ساعت ایران",
        ["Btn_Pause"] = "توقف موقت نگهبان",
        ["Btn_Resume"] = "ادامه نگهبانی",
        ["Btn_ChangeNow"] = "تغییر ساعت",
        ["Btn_SkipSession"] = "نادیده گرفتن قانون ساعت",
        ["Btn_RestoreRules"] = "برگرداندن قانون ساعت",
        ["Btn_Refresh"] = "به‌روزرسانی",
        ["Btn_Save"] = "ذخیره تغییرات",
        ["Btn_Saved"] = "ذخیره شد",
        ["Btn_Reset"] = "بازگشت به پیش‌فرض",
        ["Btn_Export"] = "خروجی",
        ["Btn_Clear"] = "پاک کردن",
        ["Btn_Browse"] = "انتخاب فایل",
        ["Btn_Install"] = "راه‌اندازی",
        ["Btn_Remove"] = "حذف",
        ["Btn_Trust"] = "مطمئن",
        ["Btn_Untrust"] = "لغو اطمینان",
        ["Btn_Ignore"] = "نادیده بگیر",
        ["Btn_Unignore"] = "دوباره حساب کن",
        ["Btn_StopOne"] = "بستن",
        ["Btn_Close"] = "بستن",
        ["Btn_Minimize"] = "کوچک کردن",

        ["Banner_ClockNeeded"] = "ساعت باید تغییر کند",
        ["Banner_ClockDetail"] = "ویندوز یک بار تأیید می‌خواهد و بعد کار ادامه پیدا می‌کند.",
        ["Banner_Failed"] = "تغییر آخر انجام نشد. کلاد مسدود می‌ماند.",
        ["Banner_Paused"] = "نگهبان متوقف است تا",

        ["Pause_15"] = "۱۵ دقیقه",
        ["Pause_30"] = "۳۰ دقیقه",
        ["Pause_60"] = "۱ ساعت",

        ["Proc_Title"] = "پردازش‌های منطبق",
        ["Proc_Empty"] = "چیزی در حال اجرا نیست.",
        ["Proc_Pid"] = "شناسه",
        ["Proc_Memory"] = "حافظه",
        ["Proc_Started"] = "شروع",
        ["Proc_StopAll"] = "بستن همه",
        ["Proc_Hint"] = "تشخیص فقط از روی نام برنامه است، پس اسکریپتی که اسم کلاد در آن آمده هرگز بسته نمی‌شود.",

        ["Net_Title"] = "کارت‌های شبکه",
        ["Net_Hint"] = "سبز یعنی این کارت الان به‌عنوان VPN حساب می‌شود. با «مطمئن» آن را ثابت کنید و با «نادیده بگیر» از فهرست بیرون بگذارید.",
        ["Net_Counts"] = "به‌عنوان VPN",
        ["Net_Up"] = "فعال",
        ["Net_Down"] = "غیرفعال",
        ["Net_Trusted"] = "مطمئن",
        ["Net_Ignored"] = "نادیده",
        ["Net_Idle"] = "بدون ترافیک",
        ["Net_Empty"] = "کارت شبکه‌ای پیدا نشد.",

        ["Act_Title"] = "رویدادها",
        ["Act_Empty"] = "هنوز اتفاقی نیفتاده.",

        ["Today_Title"] = "امروز",
        ["Today_Calm"] = "امروز لازم نشد چیزی بسته شود.",
        ["Today_Busy"] = "امروز محافظ وارد عمل شد.",
        ["Today_Stops"] = "بار {app} بسته شد",
        ["Today_VpnDrops"] = "بار قطعی VPN",
        ["Today_TimeZone"] = "بار تغییر ساعت",
        ["Today_Blocks"] = "بار قطع اینترنت",
        ["Today_Watching"] = "از نیمه‌شب تا حالا زیر نظر است.",
        ["Today_Last"] = "آخرین مورد ساعت",
        ["Act_Hint"] = "نگهداری تا",
        ["Act_Days"] = "روز",

        ["Set_Protection"] = "محافظت",
        ["Set_EnforceVpn"] = "الزام اتصال VPN",
        ["Set_EnforceVpn_Sub"] = "به‌محض قطع شدن تونل، کلاد بسته می‌شود.",
        ["Set_EnforceTz"] = "الزام ساعت کاری",
        ["Set_EnforceTz_Sub"] = "تا وقتی کلاد باز است، ساعت سیستم روی منطقه زیر می‌ماند.",
        ["Set_Action"] = "وقتی قانونی نقض شود",
        ["Set_Action_Stop"] = "کلاد را ببند",
        ["Set_Action_Warn"] = "فقط هشدار بده",
        ["Set_Tolerance"] = "قطعی کوتاه VPN را نادیده بگیر تا",
        ["Set_Tolerance_Sub"] = "کلاد در هر حالت بلافاصله مسدود می‌شود؛ این فقط تغییر ساعت را عقب می‌اندازد.",
        ["Set_Checks"] = "بررسی",
        ["Set_Interval"] = "بررسی هر",
        ["Set_Seconds"] = "ثانیه",

        ["Set_Zones"] = "منطقه‌های زمانی",
        ["Set_WorkZone"] = "منطقه کاری (VPN وصل)",
        ["Set_HomeZone"] = "منطقه خانه (VPN قطع)",
        ["Set_TzMode"] = "تغییر ساعت",
        ["Set_TzMode_Ask"] = "اول از من بپرس",
        ["Set_TzMode_Auto"] = "خودکار تغییر بده",
        ["Set_TzMode_Report"] = "هرگز تغییر نده",
        ["Set_Helper"] = "حذف پنجره تأیید ویندوز",
        ["Set_Helper_Sub"] = "دو کار زمان‌بندی‌شده می‌سازد که ساعت را با دسترسی مدیر عوض می‌کنند. ویندوز فقط همین یک بار تأیید می‌خواهد.",
        ["Set_Helper_On"] = "آماده است",
        ["Set_Helper_Off"] = "راه‌اندازی نشده",

        ["Set_Detection"] = "تشخیص",
        ["Set_VpnPattern"] = "الگوی نام کارت VPN",
        ["Set_ProcPattern"] = "الگوی نام پردازش کلاد",
        ["Set_Extra"] = "این‌ها هم کلاد حساب شوند",
        ["Set_Excluded"] = "این‌ها هرگز بسته نشوند",
        ["Set_CommaHint"] = "نام‌ها را با ویرگول جدا کنید.",
        ["Set_Tunnels"] = "هر کارت تونل یا dial-up را VPN حساب کن",
        ["Set_Routed"] = "تونل فقط وقتی حساب شود که ترافیک از آن رد شود",
        ["Set_Routed_Sub"] = "تیل‌اسکیل و زیروتیر و مشابهشان تمام روز وصل می‌مانند تا به دستگاه‌های دیگر برسند، بدون اینکه ترافیک اینترنت شما را جابه‌جا کنند. با روشن بودن این گزینه، تونلی که ترافیک شما از آن عبور نمی‌کند محافظت حساب نمی‌شود. کارتی که خودتان مطمئن علامت زده‌اید در هر حال حساب می‌شود.",
        ["Set_BadPattern"] = "این الگو معتبر نیست.",

        ["Set_App"] = "برنامه",
        ["Set_Startup"] = "اجرا با ویندوز",
        ["Set_StartMin"] = "اجرای پنهان در نوار وظیفه",
        ["Set_MinTray"] = "کوچک شدن به نوار وظیفه",
        ["Set_CloseTray"] = "با بستن پنجره، اجرا ادامه پیدا کند",
        ["Set_Notify"] = "نمایش اعلان‌ها",
        ["Set_NotifyProblems"] = "فقط برای مشکل‌ها",
        ["Set_Sound"] = "پخش صدا همراه هشدار",
        ["Set_Confirm"] = "پیش از بستن دستی کلاد بپرس",
        ["Set_Hotkey"] = "کلید Ctrl+Alt+K کلاد را می‌بندد",
        ["Set_ClaudePath"] = "مسیر برنامه کلاد",
        ["Set_ClaudePath_Auto"] = "خودکار پیدا شد",
        ["Set_ClaudePath_Missing"] = "پیدا نشد — دستی انتخاب کنید",

        ["Set_Look"] = "ظاهر",
        ["Set_Theme"] = "پوسته",
        ["Set_Theme_Dark"] = "تیره",
        ["Set_Theme_Light"] = "روشن",
        ["Set_Theme_System"] = "مثل ویندوز",
        ["Set_Accent"] = "رنگ {app}",
        ["Set_Language"] = "زبان",

        ["Set_Advanced"] = "نگهداری",
        ["Set_Retention"] = "نگهداری رویدادها برای",
        ["Set_DataFolder"] = "باز کردن پوشه داده‌ها",
        ["Set_ResetHint"] = "همه تنظیم‌ها به حالت اول برمی‌گردند.",
        ["Set_Transfer"] = "بردن همین تنظیم‌ها روی یک کامپیوتر دیگر",
        ["Set_TransferHint"] = "همه‌چیز ذخیره می‌شود جز کلید، که فقط مال همین کامپیوتر است.",
        ["Set_Export"] = "ذخیره در فایل",
        ["Set_Import"] = "خواندن از فایل",
        ["Set_ImportConfirm"] = "تنظیم‌های آن فایل جای تنظیم‌های اینجا را می‌گیرد. کلید شما دست‌نخورده می‌ماند.",

        ["About_What"] = "این برنامه چه می‌کند",
        ["About_Body"] = "تا وقتی برنامه کلاد باز است، Claude Watch دو شرط را نگه می‌دارد: تونل VPN برقرار باشد و ساعت سیستم روی منطقه کاری بماند. با شکستن هر کدام، همه پردازش‌های کلاد بسته می‌شوند و ساعت به منطقه خانه برمی‌گردد.",
        ["About_Warning"] = "این برنامه پردازش می‌بندد و ساعت سیستم را عوض می‌کند. هر دو عمدی است. تغییر ساعت به تأیید ویندوز نیاز دارد، مگر میان‌بر تنظیمات را راه بیندازید.",
        ["About_Version"] = "نسخه",
        ["About_Admin"] = "اجرا با دسترسی مدیر",
        ["About_NotAdmin"] = "اجرا با کاربر عادی",

        ["Tray_Open"] = "باز کردن Claude Watch",
        ["Tray_Stop"] = "همین حالا کلاد را ببند",
        ["Tray_Pause"] = "توقف ۳۰ دقیقه‌ای",
        ["Tray_Resume"] = "ادامه نگهبانی",
        ["Tray_Exit"] = "خروج",
        ["Tray_Running"] = "Claude Watch در نوار وظیفه باز است.",

        ["Confirm_Stop"] = "همه پردازش‌های کلاد بسته شوند؟",
        ["Confirm_Title"] = "SafeChat",
        ["Confirm_Reset"] = "همه تنظیم‌ها به پیش‌فرض برگردند؟",

        ["Notify_Stopped"] = "کلاد بسته شد",
        ["Notify_VpnLost"] = "VPN قطع شد",
        ["Notify_VpnBack"] = "VPN برگشت",
        ["Notify_ClockChanged"] = "ساعت عوض شد",

        ["Grace_Vpn"] = "VPN قطع شد",
        ["Grace_Clock"] = "ساعت درست نیست",
        ["Grace_Body"] = "ترافیک کلاد همین الان قطع شد. VPN را وصل کنید تا باز بماند.",
        ["Grace_BodyClock"] = "ترافیک کلاد همین الان قطع شد. با برگرداندن ساعت باز می‌ماند.",
        ["Grace_Closing"] = "بسته شدن کلاد تا",
        ["Grace_Back"] = "VPN برگشت. کلاد باز می‌ماند.",
        ["Grace_Fixed"] = "به‌موقع درست شد. کلاد باز می‌ماند.",
        ["Grace_StopNow"] = "همین حالا ببند",
        ["Set_Grace"] = "ثانیه فرصت تا بسته شدن کلاد",
        ["Set_Grace_Sub"] = "همان لحظه که قانونی نقض شود ترافیک با فایروال قطع می‌شود. این عدد فقط فرصت شماست که تونل را برگردانید تا خود برنامه بسته نشود.",
        ["Set_GraceOverlay"] = "نمایش هشدار شمارش معکوس روی همه پنجره‌ها",
        ["Set_Grace_Off"] = "بدون مهلت",
        ["Setup_Title"] = "راه‌اندازی یک‌باره",
        ["Setup_Sub"] = "کلیدهای ساعت و قانون فایروال را با هم ثبت می‌کند تا ویندوز فقط یک بار تأیید بخواهد و دیگر هرگز نپرسد. بار اول که اپ باز شود خودش اجرا می‌شود.",
        ["Setup_Ready"] = "انجام شد",
        ["Setup_Missing"] = "هنوز انجام نشده",
        ["Setup_Partial"] = "ناقص انجام شده",
        ["Setup_Run"] = "راه‌اندازی همه",
        ["Setup_Again"] = "راه‌اندازی دوباره",
        ["Setup_Declined"] = "تأیید داده نشد. نگهبان همچنان کلاد را می‌بندد، فقط موقع تغییر ساعت تأیید می‌خواهد.",
        ["Claude_Found"] = "کلاد پیدا شد",
        ["Claude_Missing"] = "کلاد روی این کامپیوتر پیدا نشد",
        ["Nav_Buy"] = "خرید",
        ["Buy_Title"] = "پلن‌ها و قیمت‌ها",
        ["Buy_Hint"] = "قیمت‌ها به تومان و با همه‌چیز. پلن را انتخاب کنید، بقیه‌اش با ما.",
        ["Buy_Toman"] = "تومان",
        ["Buy_PerMonth"] = "ماهانه",
        ["Buy_PerYear"] = "سالانه",
        ["Buy_PerSeat"] = "هر نفر، ماهانه",
        ["Buy_Popular"] = "بیشترین انتخاب",
        ["Buy_Order"] = "همین را می‌خواهم",
        ["Buy_Loading"] = "در حال گرفتن قیمت امروز…",
        ["Buy_Updated"] = "قیمت‌گذاری",
        ["Buy_Stale"] = "این قیمت‌ها کمی قدیمی‌اند. قبل از تصمیم، به‌روزرسانی کنید.",
        ["Buy_Cached"] = "قیمت‌های ذخیره‌شده، چون سرور در دسترس نبود. ممکن است عوض شده باشند.",
        ["Buy_NoServer"] = "آدرس سرور سفارش وارد نشده. در تنظیمات واردش کنید تا قیمت‌ها اینجا بیایند.",
        ["Buy_NoRate"] = "قیمت‌ها هنوز آماده نیستند. کمی بعد دوباره امتحان کنید.",
        ["Buy_Unreachable"] = "سرور در دسترس نبود. اتصالتان را ببینید و دوباره امتحان کنید.",
        ["Buy_Small"] = "هر قیمت برای همان روز است. نرخ بالا و پایین می‌رود، پس مبلغ نهایی موقع تأیید سفارش قطعی می‌شود.",
        ["Nav_Orders"] = "سفارش",

        ["Ip_Title"] = "آدرس شما",
        ["Ip_Checking"] = "در حال بررسی…",
        ["Ip_Failed"] = "آدرس خوانده نشد",
        ["Ip_Leak"] = "نشتی: این همان آدرسی است که بدون تونل داری",
        ["Ip_Copy"] = "کپی",
        ["Ip_Copied"] = "کپی شد",
        ["Ip_Source"] = "از",
        ["Ip_Home"] = "آدرس بدون تونل",

        ["Set_Firewall"] = "بستن ترافیک کلاد با فایروال",
        ["Set_Firewall_Sub"] = "بستن پروسه یک فاصله زمانی کوتاه دارد. قانون فایروال همان لحظه که قانونی نقض شود جلوی ترافیک خروجی کلاد را می‌گیرد و وقتی شرایط امن شد کنار می‌رود. ویندوز فقط موقع راه‌اندازی یک بار تأیید می‌خواهد.",
        ["Set_Firewall_On"] = "آماده",
        ["Set_Firewall_Off"] = "راه‌اندازی نشده",
        ["Fw_Blocked"] = "ترافیک بسته است",
        ["Fw_Open"] = "ترافیک باز است",
        ["Fw_Unknown"] = "وضعیت فایروال نامشخص",
        ["Fw_NoClaude"] = "اول مسیر برنامه کلاد را در تنظیمات مشخص کنید.",


        ["Upd_Available"] = "نسخه {0} آمد",
        ["Upd_Size"] = "{0} مگابایت",
        ["Upd_Downloading"] = "در حال گرفتن نسخه جدید",
        ["Upd_Checking"] = "بررسی فایل دانلود شده",
        ["Upd_Ready"] = "آماده نصب",
        ["Upd_Installing"] = "در حال نصب. برنامه بسته می‌شود و دوباره بالا می‌آید.",
        ["Upd_Failed"] = "آپدیت انجام نشد",
        ["Upd_Corrupt"] = "فایل کامل نرسید و پاک شد. دوباره بزنید.",
        ["Upd_NoReach"] = "سرور در دسترس نبود. تنظیمات و کلید شما دست نخورده است.",
        ["Upd_Looking"] = "در حال بررسی نسخه جدید...",
        ["Upd_Current"] = "نسخه {0}، به‌روز",
        ["Upd_CurrentAt"] = "نسخه {0}، آخرین بررسی ساعت {1}",
        ["Upd_Install"] = "نصب کن",
        ["Upd_Later"] = "الان نه",
        ["Upd_Check"] = "بررسی کن",
        ["Upd_Auto"] = "نسخه جدید که آمد خبر بده",
        ["Upd_Auto_Sub"] = "هر چند ساعت سرور را می‌پرسد. نسخه جدید فقط پیشنهاد می‌شود و تا نزنید نصب نمی‌شود.",
        ["Upd_Section"] = "نسخه",
        ["Upd_Logged"] = "نسخه {0} موجود است",
        ["Upd_Started"] = "نصب نسخه {0}",
        ["Upd_Notes"] = "چه چیزی عوض شد",

        ["Ord_Title"] = "سفارش اشتراک",
        ["Ord_NoServer"] = "سرویس سفارش تنظیم نشده. آدرسش را در تنظیمات وارد کنید.",
        ["Ord_Server"] = "آدرس سرویس سفارش",
        ["Ord_Plan"] = "اشتراک",
        ["Ord_Months"] = "مدت",
        ["Ord_Name"] = "نام و نام خانوادگی",
        ["Ord_Email"] = "ایمیل اکانتی که اشتراک رویش فعال شود",
        ["Ord_Contact"] = "آیدی یا شماره",
        ["Ord_ContactKind"] = "راه ارتباطی",
        ["Ord_Country"] = "کشور محل استفاده",
        ["Ord_Note"] = "توضیح (اختیاری)",
        ["Ord_Eligible"] = "تأیید می‌کنم اکانتم در کشوری استفاده می‌شود که Anthropic پشتیبانی می‌کند.",
        ["Ord_PasswordWarning"] = "رمز اکانت را هرگز نفرستید. برای پرداخت لازم نیست.",
        ["Ord_Submit"] = "ثبت سفارش",
        ["Ord_Sending"] = "در حال ارسال…",
        ["Ord_Done"] = "سفارش ثبت شد",
        ["Ord_Keep"] = "این کد را نگه دارید. هر وقت خواستید با آن وضعیت را ببینید.",
        ["Ord_Again"] = "ثبت سفارش دیگر",
        ["Ord_Track"] = "پیگیری سفارش",
        ["Ord_TrackBtn"] = "پیگیری",
        ["Ord_Months1"] = "۱ ماه",
        ["Ord_Months3"] = "۳ ماه",
        ["Ord_Months6"] = "۶ ماه",
        ["Ord_Months12"] = "۱۲ ماه",
        ["Ord_St_New"] = "ثبت شده",
        ["Ord_St_Confirmed"] = "تأیید شده",
        ["Ord_St_AwaitingPayment"] = "در انتظار تسویه",
        ["Ord_St_Paid"] = "پرداخت شد",
        ["Ord_St_Done"] = "انجام شد",
        ["Ord_St_Cancelled"] = "لغو شد",
        ["Ord_Err_no_server"] = "سرویس سفارش تنظیم نشده.",
        ["Ord_Err_network"] = "ارتباط با سرویس برقرار نشد.",
        ["Ord_Err_timeout"] = "سرویس به‌موقع جواب نداد.",
        ["Ord_Err_bad_email"] = "ایمیل درست وارد نشده.",
        ["Ord_Err_bad_name"] = "نام و نام خانوادگی را وارد کنید.",
        ["Ord_Err_bad_contact"] = "راه ارتباطی درست وارد نشده.",
        ["Ord_Err_unknown_plan"] = "این اشتراک در دسترس نیست.",
        ["Ord_Err_eligibility_required"] = "باید تیک تأیید را بزنید.",
        ["Ord_Err_too_many"] = "درخواست زیاد بود. بعداً دوباره تلاش کنید.",
        ["Ord_Err_not_found"] = "سفارشی با این کد پیدا نشد.",
        ["Ord_Err_failed"] = "ثبت نشد."
    };
}
